### ISSUE TITLE
Codespace unable to start in Jupyter using python feature with option "installJupyterLab": true 

### ISSUE THREAD

**Issue by prabhakk-mw** [devcontainers/features#870] opened 2024-02-20 13:36 UTC
Listed below is the `devcontainer.json` file that I am using to start a codespace on GitHub.

```JSON
{
  "name": "Only Jupyter",
  "image": "mcr.microsoft.com/devcontainers/base:ubuntu",
  "hostRequirements": {
    "cpus": 4
  },
  "features": {
    "ghcr.io/devcontainers/features/python": {
      "version": "3.10",
      "installJupyterlab": true,
      "configureJupyterlabAllowOrigin": "*"
    }
  },
  "containerUser": "vscode"
}
```

When attempting to open in `Jupyter`  as shown in the image below:
![image](https://github.com/devcontainers/features/assets/64955767/32d5d7aa-4526-4dc7-95de-6c5013fb8492)

I get the following error:
![image](https://github.com/devcontainers/features/assets/64955767/45c721b1-2c5d-4b21-86ad-ab3e5259773a)

The documentation for [opening-your-codespace-in-jupyterlab ](https://docs.github.com/en/codespaces/developing-in-a-codespace/getting-started-with-github-codespaces-for-machine-learning#opening-your-codespace-in-jupyterlab) seems to suggest that this should be all I need to do.

Restarting the codespace as the option suggests has no effect.

I can however, open in VSCode, and start `jupyter lab` from the terminal and access it in a separate browser tab.

Any help would be much appreciated!

**Comment by prabhakk-mw** [comment] 2024-02-21 04:54
Tagging for visibility: @jungaretti  @samruddhikhandale

**Comment by samruddhikhandale** [comment] 2024-02-22 00:52
Hi 👋 

Can you try with the following `.devcontainer.json`?

```json
{
  "name": "Only Jupyter",
  "image": "mcr.microsoft.com/devcontainers/universal:2",
  "hostRequirements": {
    "cpus": 4
  }
}
```

 I vaguely remember there needs another configuration change (when using Python Feature) which doesn't seem to be documented.

**Comment by prabhakk-mw** [comment] 2024-02-22 09:06
Thank you @samruddhikhandale,

Yes, the "mcr.microsoft.com/devcontainers/universal:2" image opens with the Jupyterlab editor. Probably because it already has Jupyter installed within it.

This image works with JupyterLab, with or **without** the python feature.

However, my goal is to **use features** to introduce the Python & JupyterLab into an image that **didn't** already have it; and then use that image to start in Codespace's Jupyter Editor.

The "mcr.microsoft.com/devcontainers/universal:2" image is over 13.7GB, way more than what I need in my containers.

Any other thoughts?

Could it be because of the `containerUser` specification?

**Comment by jungaretti** [comment] 2024-02-22 18:53
Is this a problem with the `$PATH` variable in the `base` image?

JupyterLab is installed in the `$HOME/.local/bin/` directory. If I remember correctly, this directory is only included in `$PATH` for login shells.

We hardcode this value into the non-login `$PATH` in the universal image, but not in other images: https://github.com/devcontainers/images/blob/9bb5c4f0540a9a54b0d4ea4151b737c7af2f8aec/src/universal/.devcontainer/local-features/setup-user/install.sh#L92

**Comment by prabhakk-mw** [comment] 2024-02-23 09:50
Surprisingly, These problematic containers do have `jupyter available on path` As shown below:
```bash
@prabhakk-mw ➜ /workspaces/matlab-codespaces (mybranch) $ which jupyter
/home/vscode/.local/bin/jupyter

@prabhakk-mw ➜ /workspaces/matlab-codespaces (mybranch) $ python -m pip show jupyterlab | grep -i location
Location: /home/vscode/.local/lib/python3.10/site-packages
```

I can even start JuptyerLab in the terminal and click on the link to view the Lab console, albeit with a refresh of the vscode interface:

```bash
prabhakk-mw ➜ /workspaces/matlab-codespaces (deleteme) $ jupyter lab
[I 2024-02-23 09:45:25.096 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-02-23 09:45:25.100 ServerApp] jupyter_server_mathjax | extension was successfully linked.
[I 2024-02-23 09:45:25.102 ServerApp] jupyter_server_terminals | extension was successfully linked.
[W 2024-02-23 09:45:25.104 LabApp] 'allow_origin' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2024-02-23 09:45:25.106 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-02-23 09:45:25.107 ServerApp] jupyterlab_git | extension was successfully linked.
[I 2024-02-23 09:45:25.107 ServerApp] nbdime | extension was successfully linked.
[I 2024-02-23 09:45:25.108 ServerApp] Writing Jupyter server cookie secret to /home/vscode/.local/share/jupyter/runtime/jupyter_cookie_secret
[I 2024-02-23 09:45:25.322 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-02-23 09:45:25.336 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-02-23 09:45:25.338 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-02-23 09:45:25.338 ServerApp] jupyter_server_mathjax | extension was successfully loaded.
[I 2024-02-23 09:45:25.339 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-02-23 09:45:25.340 LabApp] JupyterLab extension loaded from /home/vscode/.local/lib/python3.10/site-packages/jupyterlab
[I 2024-02-23 09:45:25.341 LabApp] JupyterLab application directory is /home/vscode/.local/share/jupyter/lab
[I 2024-02-23 09:45:25.341 LabApp] Extension Manager is 'pypi'.
[I 2024-02-23 09:45:25.370 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-02-23 09:45:25.374 ServerApp] jupyterlab_git | extension was successfully loaded.
[I 2024-02-23 09:45:25.412 ServerApp] nbdime | extension was successfully loaded.
[I 2024-02-23 09:45:25.413 ServerApp] Serving notebooks from local directory: /workspaces/matlab-codespaces
[I 2024-02-23 09:45:25.413 ServerApp] Jupyter Server 2.12.5 is running at:
[I 2024-02-23 09:45:25.413 ServerApp] http://localhost:8888/lab?token=5ae6f9cf1ff0bac6f94a55f1332d7cfc85361f2625cf1959
[I 2024-02-23 09:45:25.413 ServerApp]     http://127.0.0.1:8888/lab?token=5ae6f9cf1ff0bac6f94a55f1332d7cfc85361f2625cf1959
[I 2024-02-23 09:45:25.413 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-02-23 09:45:25.417 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/vscode/.local/share/jupyter/runtime/jpserver-2104-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=5ae6f9cf1ff0bac6f94a55f1332d7cfc85361f2625cf1959
        http://127.0.0.1:8888/lab?token=5ae6f9cf1ff0bac6f94a55f1332d7cfc85361f2625cf1959
```

Clicking on the last link does open up **JuptyerLab**, but still requires me to copy-paste the token into the authentication page that is presented.

![image](https://github.com/devcontainers/features/assets/64955767/70a5d85c-9833-465e-8383-e1180147372c)

Pasting the token from VSCode terminal lets me through.

The exact same image fails when you attempt to open it through 
![image](https://github.com/devcontainers/features/assets/64955767/efd6417e-2499-4daa-8608-434d44c666bd)

Does this error message at the bottom of the presented screen mean anything to you guys?
Do you know of anyone on the codespace team that could help?

![image](https://github.com/devcontainers/features/assets/64955767/d260eaff-40e8-48fa-864e-f7d5f16f9a8f)

**Comment by samruddhikhandale** [comment] 2024-02-27 18:55
> Is this a problem with the `$PATH` variable in the `base` image?
> 
> JupyterLab is installed in the `$HOME/.local/bin/` directory. If I remember correctly, this directory is only included in `$PATH` for login shells.
> 
> We hardcode this value into the non-login `$PATH` in the universal image, but not in other images: https://github.com/devcontainers/images/blob/9bb5c4f0540a9a54b0d4ea4151b737c7af2f8aec/src/universal/.devcontainer/local-features/setup-user/install.sh#L92

Thanks @jungaretti for pointing it out, and yes ^ this is the dev container configuration change needed for a codespace to be opened with JupyeterLab.

@prabhakk-mw Can you add a [similar change](https://github.com/devcontainers/images/blob/9bb5c4f0540a9a54b0d4ea4151b737c7af2f8aec/src/universal/.devcontainer/local-features/setup-user/install.sh#L92) with `:/home/${USERNAME}/.local/bin` added to PATH in your Dockerfile? Let us know if that helps.

Looping in Codespaces PM @craiglpeters, this is a known gap ^ in our documents where the Python Feature don't work without the `PATH` change. We should update our docs to reflect it until this gets fixed in the code. (Last we check, we ran into multiple issues to fix it on Codespaces end, hence, the doc updates should help avoid such confusions in the meanwhile)

**Comment by jungaretti** [comment] 2024-02-27 20:11
> Surprisingly, These problematic containers do have `jupyter available on path`

@prabhakk-mw It looks like you are using a login shell that adds the `$HOME/.local/bin/` to your `PATH` variable. This directory is scoped to a certain user (with `$HOME`) and relies on a login shell. To accurately reproduce this bug, you need to use a non-login shell.

You can use `docker run` in a Codespace to test this.

## `base` Image

Command: `docker run --rm mcr.microsoft.com/devcontainers/base:ubuntu /bin/sh -c 'echo $PATH'`

```txt
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**`/home/vscode/.local/bin` is missing from this `PATH` variable.**

## `universal:2` image

Command: `docker run --privileged --rm mcr.microsoft.com/devcontainers/universal:2 /bin/sh -c 'echo $PATH'`

```txt
/home/codespace/.dotnet:/home/codespace/nvm/current/bin:/home/codespace/.php/current/bin:/home/codespace/.python/current/bin:/home/codespace/java/current/bin:/home/codespace/.ruby/current/bin:/home/codespace/.local/bin:/usr/local/python/current/bin:/usr/local/py-utils/bin:/usr/local/oryx:/usr/local/go/bin:/go/bin:/usr/local/sdkman/bin:/usr/local/sdkman/candidates/java/current/bin:/usr/local/sdkman/candidates/gradle/current/bin:/usr/local/sdkman/candidates/maven/current/bin:/usr/local/sdkman/candidates/ant/current/bin:/usr/local/rvm/gems/default/bin:/usr/local/rvm/gems/default@global/bin:/usr/local/rvm/rubies/default/bin:/usr/local/share/rbenv/bin:/usr/local/php/current/bin:/opt/conda/bin:/usr/local/nvs:/usr/local/share/nvm/current/bin:/usr/local/hugo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/share/dotnet:~/.dotnet/tools
```

This `PATH` variable contains `/home/codespace/.local/bin` and works as expected.

**Comment by 12rambau** [comment] 2024-05-30 08:46
I created a dedicated branch on my repo that point to the exact last version of the python feature (1.6.0): https://github.com/gee-community/ipygee/tree/test-jupyterlab

I created a codespace that still works fine on VS code (https://github.com/gee-community/ipygee/codespaces) but still fail to run in jupyterlab. So unfortunately it seems we are back to square 1.

```
{
  "name": "Python 3",
  "image": "mcr.microsoft.com/devcontainers/python:1-3.11-bullseye",
  "features": {
    "ghcr.io/devcontainers/features/python:1.6.0": {
      "installJupyterlab": true
    },
    "ghcr.io/devcontainers-contrib/features/nox:2": {},
    "ghcr.io/devcontainers-contrib/features/pre-commit:2": {}
  },
  "postCreateCommand": "python -m pip install commitizen && pre-commit install"
}
```

@prabhakk-mw did you try your solution from your side ? If yes can you explain what I did wrong ?

**Comment by prabhakk-mw** [comment] 2024-05-30 09:43
@12rambau I also confirm that the fix proposed in  https://github.com/devcontainers/features/issues/870#issuecomment-1967513160 which was implemented in #887 does NOT fix the issue.

Now when I start the codespace, `jupyter` is on PATH and is also present in the `sudoers.d` file as shown below:
```bash
@prabhakk-mw ➜ /workspaces/test-matlab-codespaces (main) $ which jupyter
/home/vscode/.local/bin/jupyter
@prabhakk-mw ➜ /workspaces/test-matlab-codespaces (main) $ sudo cat /etc/sudoers.d/vscode
vscode ALL=(root) NOPASSWD:ALL
Defaults secure_path=/home/vscode/.local/bin:/usr/local/python/3.10.14/bin:/usr/local/python/current/bin:/usr/local/py-utils/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/py-utils/bin
@prabhakk-mw ➜ /workspaces/test-matlab-codespaces (main) $ 
```
@jungaretti do you have any ideas as to why this might be happening?

The `devcontainer.json` file I used was:
```JSON
{
  "name": "Only Jupyter",
  "image": "mcr.microsoft.com/devcontainers/base:ubuntu",
  "hostRequirements": {
    "cpus": 4
  },
  "features": {
    "ghcr.io/devcontainers/features/python": {
      "version": "3.10",
      "installJupyterlab": true,
      "configureJupyterlabAllowOrigin": "*"
    }
  },
  "containerUser": "vscode"
}

```
@samruddhikhandale , can you please reopen this issue?

**Comment by jcansdale** [comment] 2024-05-30 10:08
@prabhakk-mw,

Have you had any luck getting this working with the changes in https://github.com/devcontainers/features/pull/887 ?

I tried using the following `devcontainer.json`.

```json
{
  "name": "Only Jupyter",
  "image": "mcr.microsoft.com/devcontainers/base:ubuntu",
  "hostRequirements": {
    "cpus": 4
  },
  "features": {
    "ghcr.io/devcontainers/features/python:1.6.0": {
      "version": "3.10",
      "installJupyterlab": true,
      "configureJupyterlabAllowOrigin": "*"
    }
  },
  "containerUser": "vscode"
}
```

...but see the following error.

```
Failed to load the JupyterLab workbench: Unable to start server.
```

Thanks for any suggestions!

**Comment by 12rambau** [comment] 2024-05-30 11:56
> Have you had any luck getting this working with the changes in https://github.com/devcontainers/features/pull/887 ?

yes if you look at my current branch, I'm force pointing to 1.6.0 hich includes changes made in #887, still no luck....

**Comment by prabhakk-mw** [comment] 2024-05-30 12:27
> @prabhakk-mw,
> 
> Have you had any luck getting this working with the changes in https://github.com/devcontainers/features/pull/887 ?
> 
> I tried using the following `devcontainer.json`.
> 
> ```json
> {
>   "name": "Only Jupyter",
>   "image": "mcr.microsoft.com/devcontainers/base:ubuntu",
>   "hostRequirements": {
>     "cpus": 4
>   },
>   "features": {
>     "ghcr.io/devcontainers/features/python:1.6.0": {
>       "version": "3.10",
>       "installJupyterlab": true,
>       "configureJupyterlabAllowOrigin": "*"
>     }
>   },
>   "containerUser": "vscode"
> }
> ```
> 
> ...but see the following error.
> 
> ```
> Failed to load the JupyterLab workbench: Unable to start server.
> ```
> 
> Thanks for any suggestions!

No, @jcansdale ... It didn't work.  See https://github.com/devcontainers/features/issues/870#issuecomment-2139174342

**Comment by samruddhikhandale** [comment] 2024-05-30 22:44
Looking at the Codespace export logs, the codespace is still not able to find `jupyer`. See 👇 

![Image](https://github.com/devcontainers/features/assets/24955913/ea1bd41a-0f63-44f8-8176-340821f45d13)


Looks like we also need to add `/home/$USERNAME/.local/bin` to `containerEnv:PATH`, see [ref](https://github.com/devcontainers/images/pull/107/files#diff-6b389e6111c7128d9ae5de7375c89c3ba82a28f086c62bc506c296a08268b489L5). However, it's tricky and we currently don't have an easy way to auto-compute the user in `devcontainer-feature.json`. I wonder if we should symlink the binary to a static path and then refer it in `containerEnv`

I tested with 👇 and `Open in JupyterLab` worked. 

```jsonc
{
	"image": "mcr.microsoft.com/devcontainers/python:3.10",
	"features": {
		"ghcr.io/devcontainers/features/python:1": {
			"version": "none",
			"installTools": "false",
			"installJupyterlab": "true",
			"configureJupyterlabAllowOrigin": "*"
		}
	},
	"containerEnv": {
            // testing
            "PATH" : "/vscode/bin/linux-x64/dc96b837cf6bb4af9cd736aa3af08cf8279f7685/bin/remote-cli:/home/vscode/.local/bin:/usr/local/python/current/bin:/usr/local/py-utils/bin:/usr/local/python/current/bin:/usr/local/py-utils/bin:/usr/local/share/nvm/current/bin:/usr/local/bin:/usr/local/python/current/bin:/usr/local/py-utils/bin:/usr/local/python/current/bin:/usr/local/py-utils/bin:/usr/local/share/nvm/current/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/vscode/.local/bin"
    }
}
```

**Comment by 12rambau** [comment] 2024-06-07 06:50
I fail to understand why it's not possible to do the same as in universal ? is it because the Python/jupyter is store in the user local path ?

**Comment by jcansdale** [comment] 2024-07-02 09:46
> I fail to understand why it's not possible to do the same as in universal ? is it because the Python/jupyter is store in the user local path ?

I think it might be because universal uses [Oryx](https://github.com/microsoft/Oryx), which makes it a very different beast. This is just a hunch though.

**Comment by samruddhikhandale** [comment] 2024-09-27 20:10
This should be fixed with https://github.com/devcontainers/features/pull/887, closing!

**Comment by 12rambau** [comment] 2024-09-30 07:44
@samruddhikhandale, the comments we made in May are showing that #887 is not changing anything to the issue. What new development is solving the issue that you pointed out yourself here: https://github.com/devcontainers/features/issues/870#issuecomment-2140965887 ?

**Comment by Mathiyarasy** [comment] 2024-12-19 06:37
Completed in PR #1199

**Closed by Mathiyarasy** 2024-12-19 06:37 UTC

**Comment by 12rambau** [comment] 2024-12-22 19:29
I used all my codespaces for december, I'll check in my repositories in january once I can create new ones.

**Comment by 12rambau** [comment] 2025-01-01 11:05
Happy new years to all! 
Excelent news from my side, I checked with my personnal repository (the example I shared earlier in the thread) and it works like a charm. Thanks a lot!
