### ISSUE TITLE
`Node` feature has stopped working in ubuntu 18.04 containers

### ISSUE THREAD

**Issue by thegecko** [devcontainers/features#317] opened 2022-12-01 12:42 UTC
Until recently, it was possible to install node 16 into an ubuntu 18.04 devcontainer with:

```json
{
    "image": "ubuntu:18.04",

    "features": {
        "ghcr.io/devcontainers/features/node:1": {
            "version": "16"
        }
    }
}
```

However this now presents an error:

```bash
 > [dev_containers_target_stage 4/4] RUN cd /tmp/build-features/node_1 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh:
#0 0.189 ===========================================================================
#0 0.189 Feature       : Node.js (via nvm) and yarn
#0 0.189 Description   : Installs Node.js, nvm, yarn, and needed dependencies.
#0 0.189 Id            : ghcr.io/devcontainers/features/node
#0 0.189 Version       : 1.1.3
#0 0.189 Documentation : https://github.com/devcontainers/features/tree/main/src/node
#0 0.189 Options       :
#0 0.189     VERSION="16"
#0 0.189     NODEGYPDEPENDENCIES="true"
#0 0.189     NVMINSTALLPATH="/usr/local/share/nvm"
#0 0.189     NVMVERSION="0.39.2"
#0 0.189 ===========================================================================
#0 0.198 mesg: ttyname failed: Inappropriate ioctl for device
#0 0.201 (!) Unsupported distribution version 'bionic'. Details: https://github.com/nodejs/node/issues/42351#issuecomment-1068424442
#0 0.201 ERROR: Feature "Node.js (via nvm) and yarn" (ghcr.io/devcontainers/features/node) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/node for help troubleshooting this error.
```

Referencing the [new minimum glibc changes for node 18](https://github.com/nodejs/node/issues/42351#issuecomment-1068424442)

While I understand trying to install node 18 should raise this issue, why does it now happen for older versions?

**Comment by samruddhikhandale** [comment] 2022-12-01 16:55
Hi @thegecko 👋 

Thanks for reporting, looks like this is a recent regression. Working on fixing it.

**Comment by samruddhikhandale** [comment] 2022-12-02 17:49
Closing as fixed with https://github.com/devcontainers/features/pull/319 🚀

**Closed by samruddhikhandale** 2022-12-02 17:49 UTC
Labels: bug
