### ISSUE TITLE
`common-utils` overwrites `.zshrc` coming from image built with `common-utils` already

### ISSUE THREAD

**Issue by AliOsm** [devcontainers/features#1035] opened 2024-07-10 09:01 UTC
I'm using [`rails/ruby`](https://github.com/rails/devcontainer/pkgs/container/devcontainer%2Fimages%2Fruby) image, which already [uses](https://github.com/rails/devcontainer/blob/main/images/ruby/.devcontainer/devcontainer.json#L7-L13) `common-utils`. But I want to override some options like making Zsh the default shell and install OhMyZsh. When I add:

```json
"ghcr.io/devcontainers/features/common-utils:latest": {
  "installOhMyZsh": true,
  "configureZshAsDefaultShell": true
}
```

To my `devcontainer.json`, this `common-utils` usage overwrites the `.zshrc` coming from `rails/ruby` image, which should not happen based on [this](https://github.com/devcontainers/features/blob/main/src/common-utils/main.sh#L438-L449) `common-utils` script.

Any thoughts why this could happen?

**Comment by AliOsm** [comment] 2024-07-10 09:29
I think I found something, when I add `common-utils` as follows:

```json
"ghcr.io/devcontainers/features/common-utils:latest": {
  "installOhMyZsh": false,
  "installOhMyZshConfig": false,
  "configureZshAsDefaultShell": true
}
```

IT is not overwriting the `.zshrc` file, but enabling OhMyZsh stuff as follows:

```json
"ghcr.io/devcontainers/features/common-utils:latest": {
  "installOhMyZsh": true,
  "installOhMyZshConfig": true,
  "configureZshAsDefaultShell": true
}
```

Overwrites it. So, I think the bug lives in [this](https://github.com/devcontainers/features/blob/main/src/common-utils/main.sh#L505-L545) snippet.

**Comment by AliOsm** [comment] 2024-07-10 09:32
Specifically, [this](https://github.com/devcontainers/features/blob/main/src/common-utils/main.sh#L534) line overwrites the `.zshrc` file.

**Comment by AliOsm** [comment] 2024-07-10 09:39
So, the issue is as follows: in `rails/ruby` feature, an `rbenv` initialization line is added to the `.zshrc` file ([ref](https://github.com/rails/devcontainer/blob/main/features/ruby/install.sh#L25-L27)). When I enable OhMyZsh, `.zshrc` file changes to OhMyZsh template and the initialization line disappears, so I need to add the following to my post create script in my DevContainer setup to add the initialization again:

```bash
echo 'eval "$(rbenv init -)"' >> /home/vscode/.zshrc
eval "$(rbenv init -)"
```

**Comment by samruddhikhandale** [comment] 2024-07-10 20:57
Hi 👋 

Thanks for reporting! 

@gauravsaini04 / @prathameshzarkar9 Can either of you look into fixing the bug?

**Comment by prathameshzarkar9** [comment] 2024-07-31 10:47
Hi @samruddhikhandale ,

I have created a PR to fix this issue: [PR 1069](https://github.com/devcontainers/features/pull/1069)
Kindly review the same

**Comment by prathameshzarkar9** [comment] 2024-08-06 19:35
Hi @samruddhikhandale ,
PR is updated and the test cases in the pipeline are now succeed. Kindly review the PR once.

**Comment by samruddhikhandale** [comment] 2024-08-13 20:23
Closing as fixed with https://github.com/devcontainers/features/pull/1069. Feel free to reopen if needed, thanks!

**Comment by Mark-J-Lawrence** [comment] 2024-08-15 10:11
I think the changes to resolve this has broken devcontainers using `ghcr.io/devcontainers/features/node:1`. `node` & `npm` are not found after building the container

I have had to specify `ghcr.io/devcontainers/features/common-utils:2.4.5` to get it building with `node` & `npm` again.

**Comment by samruddhikhandale** [comment] 2024-08-15 16:29
Thanks for letting us know, I have reverted the changes. See https://github.com/devcontainers/features/pull/1094

@prathameshzarkar9 Can you take a look at the issue and merge the changes with the fix?

**Comment by prathameshzarkar9** [comment] 2024-09-02 09:15
Hi @Mark-J-Lawrence ,
We tried to reproduce the scenario but it is not reproducing in our codespace. Can you help us and provide a `.devcontainer` configuration file content to check what base image you are using and other configuration attributes values to have exact match with your usecase so that we would be able to trobleshoot and find the exact root cause.?

**Comment by prathameshzarkar9** [comment] 2024-09-02 09:28
Hi @samruddhikhandale ,
I have created new PR https://github.com/devcontainers/features/pull/1111 to fix this issue.
kindly review the same

**Comment by Mark-J-Lawrence** [comment] 2024-09-02 09:30
@prathameshzarkar9 
```json
{
  "name": "cics-security-sdv-samples Container",
  "build": {
    "dockerfile": "Dockerfile"
  },
  "customizations": {
    "vscode": {
      "settings": {
        "vsintellicode.java.completionsEnabled": false,
        "vsintellicode.python.completionsEnabled": false,
        "vsintellicode.sql.completionsEnabled": false,
        "vsintellicode.typescript.completionsEnabled": false,
        "vsintellicode.modify.editor.suggestSelection": "disabled",
        "errorLens.onSave": true,
        "errorLens.messageEnabled": true,
        "versionlens.suggestions.showOnStartup": true,
        "editor.formatOnSave": true,
        "ansible.python.interpreterPath": "/usr/local/python/current/bin/python",
        "pylint.interpreter": [
          "/usr/local/python/current/bin/python"
        ],
        "eslint.workingDirectories": [
          "./docs",
          "./lib"
        ],
        "stylelint.validate": [
          "css",
          "scss"
        ],
        "stylelint.configBasedir": "./docs"
      },
      "extensions": [
        "dbaeumer.vscode-eslint",
        "usernamehw.errorlens",
        "igorsbitnev.error-gutters",
        "wayou.vscode-todo-highlight",
        "pflannery.vscode-versionlens",
        "bierner.markdown-emoji",
        "redhat.ansible",
        "ms-python.flake8",
        "gruntfuggly.todo-tree",
        "ms-python.python",
        "ms-python.pylint",
        "stylelint.vscode-stylelint"
      ]
    }
  },
  "features": {
    "ghcr.io/devcontainers/features/git:1": {},
    "ghcr.io/devcontainers/features/common-utils:2": {},
    "ghcr.io/devcontainers/features/node:1": {
      "version": "18"
    },
    "ghcr.io/devcontainers/features/python:1": {
      "version": "3.12"
    }
  },
  "forwardPorts": [
    3000,
    3001
  ],
  "privileged": true,
  "remoteUser": "root",
  "workspaceMount": "source=${localWorkspaceFolder},target=/workspaces,type=bind",
  "workspaceFolder": "/workspaces",
  "postStartCommand": "git config --global --add safe.directory /workspaces; git config commit.gpgsign false",
  "postAttachCommand": "/post_script/initialise_dev_container.sh"
}
```

**Comment by prathameshzarkar9** [comment] 2024-09-02 09:39
Hi @Mark-J-Lawrence ,
Can you provide Dockerfile also just to verify the impact.

**Comment by Mark-J-Lawrence** [comment] 2024-09-02 09:41
@prathameshzarkar9 sure....

```
FROM mcr.microsoft.com/devcontainers/base:jammy

RUN apt update

ENV LOG_LEVEL="trace"

EXPOSE 3000
EXPOSE 3001

COPY initialise_dev_container.sh /post_script/initialise_dev_container.sh

RUN mkdir -p /workspaces; \
    chmod 755 /post_script/initialise_dev_container.sh

WORKDIR /workspaces
```

**Comment by samruddhikhandale** [comment] 2024-09-25 22:05
@prathameshzarkar9 Can you look at the latest details and continue investigation?

**Comment by prathameshzarkar9** [comment] 2024-10-03 05:06
Hi @samruddhikhandale ,
Latest review comments addressed. kindly review it once.

**Comment by samruddhikhandale** [comment] 2024-10-17 22:03
Completed with https://github.com/devcontainers/features/pull/1111

**Closed by samruddhikhandale** 2024-10-17 22:03 UTC
