### ISSUE TITLE
UTF-8 character in the default shell profile causes rendering issues without a $LANG or locale configured

### ISSUE THREAD

**Issue by griwes** [devcontainers/features#664] opened 2023-08-18 09:25 UTC
I've tried this with both bash and zsh. They are both broken, but in slightly different ways; I think the breakage in bash is worse, but they both are not pretty.

Steps to reproduce and demonstrate what I mean:
1. Create a bash/zsh process in a devcontainer attached to a tty.
2. Press enter repeatedly so that you are at the bottom of the tty in your terminal emulator.
3. Type in a long command that overflows the line length of your terminal emulator.
4. Run that command.
5. Next step depends on the shell being used:
    1. For bash, press the up arrow, and observe how the overflowing command does not appear fully, and how another line of text in the terminal disappears. If you now repeatedly press the down and up arrows to recall a command from history and clear it, you will see that for each of the pairs of arrow key presses, one line of text that was previously in the terminal vanishes.
    2. For zsh, press the up arrow, then the down arrow. You will see that the cursor is two cells further into the line than it should be; if you go up twice and then down, two characters from a previous command will appear in those two cells, and will not change until you force a new line to be sent to the terminal.

I believe that this is related to [this problem](https://superuser.com/questions/382456/why-does-this-bash-prompt-sometimes-keep-part-of-previous-commands-when-scrollin), though the linked original talks specifically about non-printable characters, and the arrow is definitely printable. Nevertheless, with it being a multi-byte character, it _appears_ to me that using the solution normally used for the non-printable characters, i.e. wrapping it with `\[\]` in PS1, fixes the issue for bash. I am unsure if this is a viable solution to this problem, which is why I'm filing this as an issue and not with a specific patch. I assume that the zsh method of escaping the characters in PROMPT would similarly work, but I have not verified this.

**Comment by jkeech** [comment] 2023-08-22 20:59
Walking up the stack a bit on the image where it's broken, the upstream image `buildpack-deps:jammy-curl` https://github.com/devcontainers/images/blob/main/src/base-ubuntu/.devcontainer/Dockerfile#L3 also reproduces this issue without any devcontainer-specific configuration.

```
docker run --rm -it buildpack-deps:jammy-curl
echo ➜
```

**Comment by jkeech** [comment] 2023-08-22 21:04
Looking at the Dockerfile for `buildpack-deps` and bisecting where it start breaking, it's right after `gnupg` is installed at https://github.com/docker-library/buildpack-deps/blob/93d6db0797f91ab674535553b7e0e762941a02d0/ubuntu/jammy/curl/Dockerfile#L14.

**Comment by jkeech** [comment] 2023-08-22 21:36
Opened https://github.com/docker-library/buildpack-deps/issues/148

**Comment by ridhwaans** [comment] 2024-03-04 20:58
same. does LANG not stay exported after common-utils install? 

https://github.com/devcontainers/features/blob/084df810aed51ae4a3de9b352a57a9890d5e967d/src/common-utils/main.sh#L144-L149

**Comment by lukens** [comment] 2024-12-06 16:25
Another issue I was having that seems related to this is with autocomplete in zsh. When you hit tab to autocomplete, it adds the first two characters of the pre-autocompleted command to the end of the prompt:

https://github.com/user-attachments/assets/799d21de-5f83-4eb7-aa79-1ba666a4d321

**Comment by chrmarti** [comment] 2024-12-09 10:12
Closing this as upstream since it is independent of dev containers. Unfortunately I don't know where someone would continue the investigation (as also noted in https://github.com/docker-library/buildpack-deps/issues/148#issuecomment-1851063861).

**Closed by chrmarti** 2024-12-09 10:12 UTC
Labels: bug
