### ISSUE TITLE
docker-in-docker: buildx release not found

### ISSUE THREAD

**Issue by sliekens** [devcontainers/features#556] opened 2023-05-22 21:53 UTC
Hi,

There is a temporary problem with buildx where the tag for [v0.10.5](https://github.com/docker/buildx/releases/tag/v0.10.5) was pushed, but the corresponding release was not.
![image](https://github.com/devcontainers/features/assets/1583241/b8d558d9-d8d2-4ebc-9903-a2230e2396b3)

As a result, this line is failing:
https://github.com/devcontainers/features/blob/b48d8700ffe5c0b363c9e8706ba2c1601a2bb94f/src/docker-in-docker/install.sh#L323

Logs:

```
#0 21.79 (*) Installing buildx 0.10.5...
#0 21.79 --2023-05-22 21:46:46--  https://github.com/docker/buildx/releases/download/v0.10.5/buildx-v0.10.5.linux-amd64
#0 21.80 Resolving github.com (github.com)... 140.82.121.4
#0 21.80 Connecting to github.com (github.com)|140.82.121.4|:443... connected.
#0 21.86 HTTP request sent, awaiting response... 404 Not Found
#0 22.04 2023-05-22 21:46:46 ERROR 404: Not Found.
#0 22.04 
#0 22.04 ERROR: Feature "Docker (Docker-in-Docker)" (ghcr.io/devcontainers/features/docker-in-docker) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/docker-in-docker for help troubleshooting this error.
````

**Comment by sliekens** [comment] 2023-05-22 22:35
This is now resolved but it took about 5 hours for the release to catch up.

**Comment by samruddhikhandale** [comment] 2023-05-22 23:06
Thanks for reporting the issue. 

We should add some fallback to older releases if the latest tag does not exist or add a similar logic to https://github.com/devcontainers/features/pull/318

**Comment by hpe-ykoehler** [comment] 2023-06-13 14:26
Same is occuring with v0.11.0

The issue is on the devcontainer feature, using the tags to assume that the tarball is available is a bad process as it can leads to such error.

The devcontainer feature should allow us to control the version of buildx or use the latest tarball available (not the latest tag).

**Comment by pamelafox** [comment] 2023-06-15 00:08
I think I may be seeing the same issue? I'm trying to use docker-in-docker in a dev container on GitHub Codespaces today, and getting:

```
2023-06-15 00:01:44.309Z: #20 7.281 Err:5 https://packages.microsoft.com/repos/microsoft-debian-bookworm-prod bookworm Release
#20 7.281   404  Not Found [IP: 13.93.152.112 443]
#20 7.295 Reading package lists...2023-06-15 00:01:44.760Z: 
#20 7.754 E: The repository 'https://packages.microsoft.com/repos/microsoft-debian-bookworm-prod bookworm Release' does not have a Release file.
#20 7.755 ERROR: Feature "Docker (Docker-in-Docker)" (ghcr.io/devcontainers/features/docker-in-docker) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/docker-in-docker for help troubleshooting this error.
2023-06-15 00:01:44.812Z: #20 ERROR: executor failed running [/bin/sh -c chmod -R 0755 /tmp/dev-container-features/docker-in-docker_1 && cd /tmp/dev-container-features/docker-in-docker_1 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh]: exit code: 100
------
 > [dev_containers_target_stage 5/5] RUN chmod -R 0755 /tmp/dev-container-features/docker-in-docker_1 && cd /tmp/dev-container-features/docker-in-docker_1 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh:
------
executor failed running [/bin/sh -c chmod -R 0755 /tmp/dev-container-features/docker-in-docker_1 && cd /tmp/dev-container-features/docker-in-docker_1 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh]: exit code: 100
2023-06-15 00:01:44.814Z: ERROR: Service 'app' failed to build : Build failed
```

**Comment by samruddhikhandale** [comment] 2023-06-15 00:21
> The issue is on the devcontainer feature, using the tags to assume that the tarball is available is a bad process as it can leads to such error.

Hi @hpe-ykoehler  👋 

I totally agree with change, and we are aware of this problem and have this item added to the backlog. However, very busy with other items. 

We appreciate contributions from the community, if you are interested and willing to open a PR with the changes, we will be glad. I can help review and provide any other support/guidance if needed.

**Comment by samruddhikhandale** [comment] 2023-06-15 00:23
Hi @pamelafox 👋 

I wonder if Microsoft repos have added support for docker-in-docker for `debian:bookworm`. Have you looked at https://github.com/devcontainers/images/issues/607 ? Switching the image to use `debian:bullseye` should help in the meanwhile.

**Comment by hpe-ykoehler** [comment] 2023-06-15 01:15
From the buildx side, they recommended using the GitHub release API.  Now that is not something I am familiar with, maybe supporting a version instead of a boolean is more in my league.  Will see if I can find some time.

**Comment by bseth15** [comment] 2023-11-16 22:53
This is happening again, DinD is looking for v0.12.0 and v0.11.2 is the latest release on github.

**Comment by gauravsaini04** [comment] 2024-02-19 07:34
Raised draft [PR #869](https://github.com/devcontainers/features/pull/869)

**Comment by gauravsaini04** [comment] 2024-02-23 08:55
> [!IMPORTANT]
> PR #869 was merged.

**Comment by samruddhikhandale** [comment] 2024-02-23 17:27
Closing as completed with https://github.com/devcontainers/features/pull/869

**Closed by samruddhikhandale** 2024-02-23 17:27 UTC
Labels: enhancement
