### ISSUE TITLE
Unable to install python

### ISSUE THREAD

**Issue by sarthakpati** [devcontainers/features#598] opened 2023-06-28 22:42 UTC
Hi,

I am getting a weird error from one of PRs for the devcontainer builds [[ref](https://github.com/mlcommons/GaNDLF/actions/runs/5403500193/jobs/9816395962?pr=681)]. Basically, the error is stating that python could not be installed from the ghcr packages:

```
2023-06-28T16:31:48.7395210Z [2023-06-28T16:31:48.738Z] #25 26.55 ERROR: Feature "Python" (ghcr.io/devcontainers/features/python) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/python for help troubleshooting this error.
```

I am not particularly sure why this would be case. Unfortunately, this is also blocking a very critical PR [[ref](https://github.com/mlcommons/GaNDLF/pull/681)], so any help related to this would be much appreciated.

**Comment by jkeech** [comment] 2023-06-28 22:55
I think this is because the python image used in https://github.com/mlcommons/GaNDLF/blob/master/.devcontainer/Dockerfile#L1 upgraded to Debian 12 Bookworm recently. Another interesting thing is that your devcontain config is using the Python image but it's also trying to re-install python with the Python feature: https://github.com/mlcommons/GaNDLF/blob/master/.devcontainer/devcontainer.json#L13.

You could try two things:
1) Pin the image back to Debian 11 Bullseye: `mcr.microsoft.com/devcontainers/python:3.8-bullseye`
2) Update the python feature to install JupyterLab but not try to install an additional Python version:
```
"ghcr.io/devcontainers/features/python": {
	"version": "none",
	"installJupyterlab": true
}
```

**Comment by jkeech** [comment] 2023-06-28 23:05
By the way, the failure message is directly above the spot you linked: https://github.com/mlcommons/GaNDLF/actions/runs/5403500193/jobs/9816395962?pr=681#step:8:3690. The feature fails immediately after this because the pip installation failed.

```
[2023-06-28T16:31:46.649Z] #25 24.56 Updating pip...
  
  
  [2023-06-28T16:31:48.584Z] #25 26.49 error: externally-managed-environment
  #25 26.49 
  #25 26.49 × This environment is externally managed
  #25 26.49 ╰─> To install Python packages system-wide, try apt install
  #25 26.49     python3-xyz, where xyz is the package you are trying to
  #25 26.49     install.
  #25 26.49     
  #25 26.49     If you wish to install a non-Debian-packaged Python package,
  #25 26.49     create a virtual environment using python3 -m venv path/to/venv.
  #25 26.49     Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
  #25 26.49     sure you have python3-full installed.
  #25 26.49     
  #25 26.49     If you wish to install a non-Debian packaged Python application,
  #25 26.49     it may be easiest to use pipx install xyz, which will manage a
  #25 26.49     virtual environment for you. Make sure you have pipx installed.
  #25 26.49     
  #25 26.49     See /usr/share/doc/python3.11/README.venv for more information.
  #25 26.49 
  #25 26.49 note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
  #25 26.49 hint: See PEP 668 for the detailed specification.
```

This error is a duplicate of https://github.com/devcontainers/features/issues/577 and it's tied to the new Bookworm distro.

**Closed as completed** 2023-06-29 18:04 UTC
