### ISSUE TITLE
Feature "Kubectl, Helm, and Minikube" won't install with helm latest specified

### ISSUE THREAD

**Issue by AceHack** [devcontainers/features#548] opened 2023-05-10 17:54 UTC
```
#0 9.418 Downloading Helm...
#0 9.655 HELM_VERSION=3.12.0
#0 11.50 Verification failed!
#0 11.50 gpg: no valid OpenPGP data found.
#0 11.50 gpg: the signature could not be verified.
#0 11.50 Please remember that the signature file (.sig or .asc)
#0 11.50 should be the first file given on the command line.
#0 11.50 ERROR: Feature "Kubectl, Helm, and Minikube" (ghcr.io/devcontainers/features/kubectl-helm-minikube) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/kubectl-helm-minikube for help troubleshooting this error.
------
failed to solve: process "/bin/sh -c chmod -R 0755 /tmp/dev-container-features/kubectl-helm-minikube_10 && cd /tmp/devcontainer-features/kubectl-helm-minikube_10 && chmod +x ./devcontainer-features-install.sh && ./devcontainerfeatures-install.sh" did not complete successfully: exit code: 1
```

**Comment by AceHack** [comment] 2023-05-10 18:06
I temporarily fixed this issue by changing `.devcontainer.json` as follows.  Seems a problem with the `latest` tag.
```
// https://github.com/devcontainers/features/tree/main/src/kubectl-helm-minikube
"ghcr.io/devcontainers/features/kubectl-helm-minikube:1": {
	"version": "latest",
	"helm": "latest",
	"minikube": "latest"
},
```
to
```
// https://github.com/devcontainers/features/tree/main/src/kubectl-helm-minikube
"ghcr.io/devcontainers/features/kubectl-helm-minikube:1": {
	"version": "latest",
	"helm": "3.11.3",
	"minikube": "latest"
},
```

**Comment by samruddhikhandale** [comment] 2023-05-12 01:21
Closing as duplicate of https://github.com/devcontainers/features/issues/334

**Closed by samruddhikhandale** 2023-05-12 01:21 UTC
