### ISSUE TITLE
terraform-feature: gpg: key server receive failed: No name 

### ISSUE THREAD

**Issue by iLem0n** [devcontainers/features#441] opened 2023-02-07 12:10 UTC
Setup: 
**macOS:** Ventura 13.2
**VSCode:** Version: 1.75.0 (Universal), Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
**DevContainer-Extension:** v0.275.1
**Docker-Desktop**: 4.16.2 (95914)

Problem: 
Im facing some issues using the terraform feature while building the dev container. 
As you can see at the file below I also tried other features successfully and figured out that only the terraform feature is affected.

Im not sure if it makes a difference but since im in a corporate network im using [Proxydetox](https://github.com/kiron1/proxydetox) which works totally fine on all other points. 

Steps to reproduce: 
1. create minimal project only having the file below
2. open as dev-container or open and rebuild

File: `.devcontainer/devcontainer.json`
```json
{
    "name": "Test Example",
    "image": "mcr.microsoft.com/devcontainers/base:jammy",
    "features": {	
                // "ghcr.io/devcontainers/features/azure-cli:1": {
		// 	"version": "latest"
		// },
		// "ghcr.io/devcontainers/features/kubectl-helm-minikube:1": {
		// 	"version": "latest",
		// 	"helm": "3.11.0",
		// 	"minikube": "none"
		// },
		// "ghcr.io/devcontainers/features/powershell:1": {
		// 	"version": "latest"
		// },	 
		"ghcr.io/devcontainers/features/terraform:1": {
			"version": "1.3.7",
			"tflint": "0.44.1",
			"terragrunt": "0.42.8",
			"installTFsec": true
		}
	}
}
```

Error Log: 
```
------
 > [dev_containers_target_stage 4/4] RUN cd /tmp/build-features/terraform_1 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh:
#0 0.475 ===========================================================================
#0 0.475 Feature       : Terraform, tflint, and TFGrunt
#0 0.475 Description   : Installs the Terraform CLI and optionally TFLint and Terragrunt. Auto-detects latest version and installs needed dependencies.
#0 0.475 Id            : ghcr.io/devcontainers/features/terraform
#0 0.475 Version       : 1.1.2
#0 0.475 Documentation : https://github.com/devcontainers/features/tree/main/src/terraform
#0 0.475 Options       :
#0 0.475     VERSION="1.3.7"
#0 0.475     TFLINT="0.44.1"
#0 0.475     TERRAGRUNT="0.42.8"
#0 0.475    
[2023-02-07T11:53:56.258Z]  INSTALLTFSEC="true"
#0 0.475     INSTALLTERRAFORMDOCS="false"
#0 0.475 ===========================================================================
#0 1.392 TERRAFORM_VERSION=1.3.7
#0 1.938 TFLINT_VERSION=0.44.1
[2023-02-07T11:53:56.258Z] 
#0 2.431 TERRAGRUNT_VERSION=0.42.8
#0 2.437 Downloading terraform...
#0 3.619 (*) Downloading GPG key...
#0 4.500 gpg: keyserver receive failed: No name
#0 4.502 (*) Failed getting key, retring in 10s...
[2023-02-07T11:53:56.258Z] #0 14.50 (*) Downloading GPG key...
#0 14.66 gpg: keyserver receive failed: No name
#0 14.67 (*) Failed getting key, retring in 10s...
#0 24.67 (*) Downloading GPG key...
#0 24.78 gpg: keyserver receive failed: No name
#0 24.78 (*) Failed getting key, retring in 10s...
#0 34.78 (*) Downloading GPG key...
#0 34.88 gpg: keyserver receive failed: No name
#0 34.88 (*) Failed getting key, retring in 10s...
#0 44.89 (*) Downloading GPG key...
#0 45.01 gpg: keyserver receive failed: No name
#0 45.01 (*) Failed getting key, retring in 10s...
#0 55.01 (!) Failed to get gpg key.
#0 55.01 ERROR: Feature "Terraform, tflint, and TFGrunt" (ghcr.io/devcontainers/features/terraform) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/terraform for help troubleshooting this error.
------
[2023-02-07T11:53:56.259Z] ERROR: failed to solve: executor failed running [/bin/sh -c cd /tmp/build-features/terraform_1 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh]: exit code: 1
[2023-02-07T11:53:56.275Z] Stop (62001 ms): Run: docker buildx build --load --build-context dev_containers_feature_content_source=/var/folders/2p/6p4q2yln6y5g4yqlkl4w_6fc0000gn/T/devcontainercli/container-features/0.29.0-1675770772221 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:jammy --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-example-devcontainer-502822ef8482b94ff4707eb4b9a2cbd2-features -f /var/folders/2p/6p4q2yln6y5g4yqlkl4w_6fc0000gn/T/devcontainercli/container-features/0.29.0-1675770772221/Dockerfile.extended /Users/q278134/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[2023-02-07T11:53:56.276Z] Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/var/folders/2p/6p4q2yln6y5g4yqlkl4w_6fc0000gn/T/devcontainercli/container-features/0.29.0-1675770772221 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:jammy --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-example-devcontainer-502822ef8482b94ff4707eb4b9a2cbd2-features -f /var/folders/2p/6p4q2yln6y5g4yqlkl4w_6fc0000gn/T/devcontainercli/container-features/0.29.0-1675770772221/Dockerfile.extended /Users/q278134/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[2023-02-07T11:53:56.276Z]     at fie (/Users/q278134/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1915:1355)
[2023-02-07T11:53:56.277Z]     at P7 (/Users/q278134/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1915:1291)
[2023-02-07T11:53:56.277Z]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-02-07T11:53:56.277Z]     at async Fie (/Users/q278134/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1921:2093)
[2023-02-07T11:53:56.277Z]     at async Vf (/Users/q278134/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:1921:3241)
[2023-02-07T11:53:56.277Z]     at async eoe (/Users/q278134/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:2045:17324)
[2023-02-07T11:53:56.277Z]     at async Qse (/Users/q278134/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js:2045:17065)
[2023-02-07T11:53:56.285Z] Stop (65055 ms): Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/q278134/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/q278134/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder tmp/devcontainers-dbabf0a3-a230-44d9-9763-f05fb257cb2d1675770768745 --workspace-folder /Users/q278134/Projekte/BMW/SF.D/playground/example-devcontainer --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/q278134/Projekte/BMW/SF.D/playground/example-devcontainer --id-label devcontainer.config_file=/Users/q278134/Projekte/BMW/SF.D/playground/example-devcontainer/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/q278134/Projekte/BMW/SF.D/playground/example-devcontainer/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-02-07T11:53:56.285Z] Exit code 1
[2023-02-07T11:53:56.288Z] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/q278134/.vscode/extensions/ms-vscode-remote.remote-containers-0.275.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/q278134/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder tmp/devcontainers-dbabf0a3-a230-44d9-9763-f05fb257cb2d1675770768745 --workspace-folder /Users/q278134/Projekte/BMW/SF.D/playground/example-devcontainer --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/q278134/Projekte/BMW/SF.D/playground/example-devcontainer --id-label devcontainer.config_file=/Users/q278134/Projekte/BMW/SF.D/playground/example-devcontainer/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/q278134/Projekte/BMW/SF.D/playground/example-devcontainer/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-02-07T11:53:56.288Z] Exit code 1

```

**Comment by samruddhikhandale** [comment] 2023-02-07 23:08
Closing as duplicate of https://github.com/devcontainers/features/issues/435

**Closed by samruddhikhandale** 2023-02-07 23:08 UTC
