### ISSUE TITLE
Universal image using incompatible `gradle` version in v2.0.18

### ISSUE THREAD

**Issue by cmbrose** [devcontainers/features#236] opened 2022-10-25 20:59 UTC
Between releases `v2.0.20` ([version notes](https://github.com/devcontainers/images/blob/main/src/universal/history/2.0.20.md)) and `v2.0.19` ([version notes](https://github.com/devcontainers/images/blob/main/src/universal/history/2.0.19.md)) the `gradle` version dropped to `6.9.3` from `7.5.1`. This makes the universal image unable to run gradle against Java 17 applications as gradle `>= 7.3` is required to do so.

I haven't been able to find what specifically regressed the version yet, but in the meantime the workaround is to install the higher version manually using `sdk install gradle`.

**Comment by cmbrose** [comment] 2022-10-26 00:34
For more details on the investigation, see https://github.com/orgs/community/discussions/37051

**Comment by samruddhikhandale** [comment] 2022-10-28 18:12
We released a new version for the `universal` image yesterday which contains `Gradle - 7.5.1`. 
https://github.com/devcontainers/images/blob/main/src/universal/history/2.0.21.md

Looks like the issue is now resolved, I'll investigate why the regression happened. As the `java` feature always installs `latest` of gradle, unless it was an issue with java sdk, nothing else jumps out to me.

**Comment by samruddhikhandale** [comment] 2022-10-28 18:13
Closing as fixed in the `universal:latest` image.

**Closed by samruddhikhandale** 2022-10-28 18:13 UTC

**Comment by schrum2** [comment] 2022-11-01 04:32
@cmbrose A brand new codespace with the new image is able to complete a gradle build, but the default command line Java is apparently not the same version that gradle is building with, as demonstrated by this test run:
```
@schrum2 ➜ /workspaces/CS2A5-RecursiveBioinformatics (main) $ gradle build

Welcome to Gradle 7.5.1!

Here are the highlights of this release:
 - Support for Java 18
 - Support for building with Groovy 4
 - Much more responsive continuous builds
 - Improved diagnostics for dependency resolution

For more details see https://docs.gradle.org/7.5.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Task :test

TestTest > test() PASSED

BUILD SUCCESSFUL in 19s
4 actionable tasks: 4 executed
@schrum2 ➜ /workspaces/CS2A5-RecursiveBioinformatics (main ✗) $ java -jar build/libs/CS2A5-RecursiveBioinformatics.jar 
Error: LinkageError occurred while loading main class bio.Test
        java.lang.UnsupportedClassVersionError: bio/Test has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
@schrum2 ➜ /workspaces/CS2A5-RecursiveBioinformatics (main ✗) $
```

**Comment by cmbrose** [comment] 2022-11-02 20:50
@schrum2 thanks for raising this again - I think that this is captured in https://github.com/devcontainers/images/issues/187 due to the 2 java paths. If so, @samruddhikhandale is working on that as well.
