### ISSUE TITLE
Can't install jupyterlab in debian-slim

### ISSUE THREAD

**Issue by pamelafox** [devcontainers/features#588] opened 2023-06-21 20:36 UTC
Here's my setup:

```
FROM debian:bullseye-slim
```

devcontainer.json:

```
{
	"name": "Data 8 notebooks",
	"build": {
		"dockerfile": "dockerfile",
		"context": ".."
	},
	"features": {
		"ghcr.io/devcontainers/features/python:1": {
			"version": "3.11",
			"installJupyterlab": true
		}
	},
```

That results in this error:

```
#18 325.5 ./install.sh: line 307: /usr/local/python/3.11.4/bin/python3 -m pip install --user --upgrade --no-cache-dir jupyterlab: No such file or directory
#18 325.5 ERROR: Feature "Python" (ghcr.io/devcontainers/features/python) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/python for help troubleshooting this error.
```

Notably, I'm intentionally using a Debian that has no built-in Python package, as I'm trying to create an image with a single Python version. So maybe the PYTHON_SRC logic isn't compatible with that?

**Comment by samruddhikhandale** [comment] 2023-06-22 00:02
HI 👋 

@alexander-smolyakov can you help investigate? thanks! 

@pamelafox  In the meanwhile, can you use the `mcr.microsoft.com/devcontainers/base:bullseye` image instead? Dev container was successfully created with it 👇 

![image](https://github.com/devcontainers/features/assets/24955913/4aae8d79-ae6a-43f9-a7b9-b55e37122c53)

**Comment by pamelafox** [comment] 2023-06-22 03:07
Thanks @samruddhikhandale - that does build, but I believe it also has a base Python version   from the OS (try running `python 3.9`). I'm using slim to avoid that, and only have one version.

Also, I haven't managed to get that one to load in Jupyterlab (from "your codespaces" tab), but I'll bring that up with Codespaces team.

**Comment by alexander-smolyakov** [comment] 2023-09-28 09:03
Hey @pamelafox, we have merged the fix for the Python feature. Could you please check if the issue is resolved now?

Link to fix:
- #694

**Comment by alexander-smolyakov** [comment] 2023-10-09 14:50
I'm closing this issue since it was resolved. Feel free to request a reopening if the issue still occurs.

**Closed by alexander-smolyakov** 2023-10-09 14:50 UTC
